# Generated by Django 5.2.5 on 2025-08-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='', max_length=3)),
                ('title', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MySocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsApp', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55)),
                ('description', models.CharField(default='', max_length=255)),
                ('quantity', models.CharField(default='', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='LuNuts', max_length=15)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('home_description', models.CharField(default='Nossos Produtos', max_length=255)),
                ('product_title', models.CharField(default='Nossos Produtos', max_length=15)),
                ('about_title', models.CharField(default='Sobre a LUNUTS', max_length=15)),
                ('about_description', models.TextField(blank=True, null=True)),
                ('contact_Title', models.CharField(default='Entre em Contato', max_length=25)),
            ],
        ),
    ]
