# Generated by Django 5.2.5 on 2025-08-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='website_title',
            field=models.CharField(default='LUNUTS - Castanhas de Caju', max_length=32),
        ),
    ]
