# Generated by Django 5.2.5 on 2025-08-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_siteconfig_website_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='contact_Title',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='product_title',
        ),
    ]
