# Generated by Django 5.2.5 on 2025-08-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_siteconfig_about_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='banner_image',
            new_name='home_image',
        ),
    ]
