# Generated by Django 5.2.5 on 2025-08-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_banner_image_siteconfig_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='home_description',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
