# Generated by Django 5.2.5 on 2025-08-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_siteconfig_home_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_description',
            field=models.CharField(default='Sabor autêntico, selecionado à mão, com foco em qualidade, tradição e sustentabilidade.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_title',
            field=models.CharField(default='Frescas, deliciosas e direto de Manjacaze', max_length=55),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_description',
            field=models.TextField(default='Nascida em Manjacaze, a LUNUTS dedica-se à seleção e transformação de castanha de caju com rigor e carinho. Trabalhamos com produtores locais, valorizando o saber tradicional e promovendo práticas que respeitam o ambiente.', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='mission',
            field=models.TextField(default='Levar o melhor sabor de Manjacaze a todo o país, criando impacto social positivo e rendimentos justos para as comunidades locais.', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='skill',
            field=models.TextField(default='Qualidade, Confiança, Tradição', max_length=55),
        ),
    ]
