# Generated by Django 5.2.5 on 2025-08-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_siteconfig_home_description_siteconfig_home_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Skill',
        ),
        migrations.AlterField(
            model_name='mysocialmedia',
            name='instagram',
            field=models.URLField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mysocialmedia',
            name='whatsApp',
            field=models.URLField(default='', max_length=40),
        ),
    ]
