# Generated by Django 5.2.5 on 2025-08-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_about_skill_alter_mysocialmedia_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysocialmedia',
            old_name='whatsApp',
            new_name='whatsapp',
        ),
    ]
