# Generated by Django 5.2.5 on 2025-08-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_whatsapp_mysocialmedia_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=75)),
            ],
        ),
    ]
