# Generated by Django 5.2.5 on 2025-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_faqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faqs',
            new_name='Faq',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(default='', max_length=35),
        ),
    ]
