# Generated by Django 5.2.5 on 2025-08-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_faqs_faq_remove_skill_emoji_alter_skill_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='skill',
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mysocialmedia',
            name='instagram',
            field=models.URLField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/home/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('product_type', models.CharField(default='Normal', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
