# Generated by Django 5.2.5 on 2025-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_siteconfig_skill_alter_faq_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.CharField(default='', max_length=8),
        ),
    ]
