# Generated by Django 5.2.5 on 2025-08-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contactformlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormLog',
        ),
    ]
