# Generated by Django 5.2.5 on 2025-08-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contactformlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='FrequentlyAskedQuestion',
        ),
    ]
