# Generated by Django 5.2.5 on 2025-08-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cartformlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartformlog',
            old_name='cart_Item',
            new_name='cart_item',
        ),
    ]
