# Generated by Django 5.2.5 on 2025-08-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_cart_item_cartformlog_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartformlog',
            name='cart_item',
            field=models.TextField(null=True),
        ),
    ]
