# Generated by Django 5.2.5 on 2025-08-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_cartformlog_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='website_logo',
            field=models.ImageField(blank=True, default='static/img/logo.png', null=True, upload_to='static/img/logo/'),
        ),
    ]
